"""add vector extension and AI embeddings

Revision ID: 25e90a154882
Revises: 6304e81ff05a
Create Date: 2026-03-10 14:25:51.538621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '25e90a154882'
down_revision: Union[str, Sequence[str], None] = '6304e81ff05a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brain_entries', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('brain_entries', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.drop_constraint(op.f('brain_entries_user_id_fkey'), 'brain_entries', type_='foreignkey')
    op.create_foreign_key(None, 'brain_entries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brain_entries', type_='foreignkey')
    op.create_foreign_key(op.f('brain_entries_user_id_fkey'), 'brain_entries', 'users', ['user_id'], ['id'])
    op.drop_column('brain_entries', 'embedding')
    op.drop_column('brain_entries', 'updated_at')
    # ### end Alembic commands ###
